<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Dock;

class DockSeeder extends Seeder
{
    public function run(): void
    {
        Dock::truncate();

        $docks = [
            [
                'routinav_id' => 1,
                'nome'        => 'Bico',
                'latitude'    => 40.728333,
                'longitude'   => -8.648333,
                'tipo'        => 'secundario',
                'imagem'      => null,
                'descricao'   => null,
            ],
            [
                'routinav_id' => 3,
                'nome'        => 'Bestida',
                'latitude'    => 40.76067,
                'longitude'   => -8.679062,
                'tipo'        => 'secundario',
                'imagem'      => null,
                'descricao'   => null,
            ],
            [
                'routinav_id' => 4,
                'nome'        => 'Salreu',
                'latitude'    => 40.728198,
                'longitude'   => -8.582032,
                'tipo'        => 'secundario',
                'imagem'      => null,
                'descricao'   => null,
            ],
            [
                'routinav_id' => 5,
                'nome'        => 'Torreira',
                'latitude'    => 40.760435,
                'longitude'   => -8.699841,
                'tipo'        => 'secundario',
                'imagem'      => null,
                'descricao'   => null,
            ],
            [
                'routinav_id' => 6,
                'nome'        => 'ANGE',
                'latitude'    => 40.613998,
                'longitude'   => -8.73978,
                'tipo'        => 'secundario',
                'imagem'      => null,
                'descricao'   => null,
            ],
            [
                'routinav_id' => 7,
                'nome'        => 'Costa Nova',
                'latitude'    => 40.62,
                'longitude'   => -8.748333,
                'tipo'        => 'secundario',
                'imagem'      => null,
                'descricao'   => null,
            ],
            [
                'routinav_id' => 8,
                'nome'        => 'Jardim Oudinot',
                'latitude'    => 40.643655,
                'longitude'   => -8.731764,
                'tipo'        => 'turistico',
                'imagem'      => null,
                'descricao'   => null,
            ],
            [
                'routinav_id' => 9,
                'nome'        => 'Vagueira',
                'latitude'    => 40.560839,
                'longitude'   => -8.757627,
                'tipo'        => 'secundario',
                'imagem'      => null,
                'descricao'   => null,
            ],
            [
                'routinav_id' => 11,
                'nome'        => 'APARA',
                'latitude'    => 40.63106,
                'longitude'   => -8.733562,
                'tipo'        => 'principal',
                'imagem'      => null,
                'descricao'   => null,
            ],
            [
                'routinav_id' => 12,
                'nome'        => 'Ponte da Barra',
                'latitude'    => 40.629849,
                'longitude'   => -8.738117,
                'tipo'        => 'secundario',
                'imagem'      => null,
                'descricao'   => null,
            ],
            [
                'routinav_id' => 13,
                'nome'        => 'Varela',
                'latitude'    => 40.790231,
                'longitude'   => -8.672809,
                'tipo'        => 'secundario',
                'imagem'      => null,
                'descricao'   => null,
            ],
            [
                'routinav_id' => 14,
                'nome'        => 'Carregal',
                'latitude'    => 40.859204,
                'longitude'   => -8.656774,
                'tipo'        => 'secundario',
                'imagem'      => null,
                'descricao'   => null,
            ],
            [
                'routinav_id' => 15,
                'nome'        => 'Moranzel',
                'latitude'    => 40.720167,
                'longitude'   => -8.692863,
                'tipo'        => 'secundario',
                'imagem'      => null,
                'descricao'   => null,
            ],
            [
                'routinav_id' => 16,
                'nome'        => 'São Jacinto',
                'latitude'    => 40.653862,
                'longitude'   => -8.732636,
                'tipo'        => 'secundario',
                'imagem'      => null,
                'descricao'   => null,
            ],
            [
                'routinav_id' => 17,
                'nome'        => 'Terminal Norte',
                'latitude'    => 40.659839,
                'longitude'   => -8.702271,
                'tipo'        => 'principal',
                'imagem'      => null,
                'descricao'   => null,
            ],
            [
                'routinav_id' => 18,
                'nome'        => 'Terminal Sul',
                'latitude'    => 40.63853,
                'longitude'   => -8.689925,
                'tipo'        => 'principal',
                'imagem'      => null,
                'descricao'   => null,
            ],
            [
                'routinav_id' => 19,
                'nome'        => 'Lota',
                'latitude'    => 40.646162,
                'longitude'   => -8.663814,
                'tipo'        => 'principal',
                'imagem'      => null,
                'descricao'   => null,
            ],
            [
                'routinav_id' => 20,
                'nome'        => 'Rio Novo do Príncipe',
                'latitude'    => 40.694808,
                'longitude'   => -8.637975,
                'tipo'        => 'secundario',
                'imagem'      => null,
                'descricao'   => null,
            ],
            [
                'routinav_id' => 21,
                'nome'        => 'Parrachil',
                'latitude'    => 40.678333,
                'longitude'   => -8.676667,
                'tipo'        => 'secundario',
                'imagem'      => null,
                'descricao'   => null,
            ],
            [
                'routinav_id' => 22,
                'nome'        => 'Lavacos',
                'latitude'    => 40.665056,
                'longitude'   => -8.716192,
                'tipo'        => 'secundario',
                'imagem'      => null,
                'descricao'   => null,
            ],
            [
                'routinav_id' => 23,
                'nome'        => 'Arieiros',
                'latitude'    => 40.713555,
                'longitude'   => -8.645284,
                'tipo'        => 'secundario',
                'imagem'      => null,
                'descricao'   => null,
            ],
            [
                'routinav_id' => 24,
                'nome'        => 'Ilha dos Ovos / Amoroso',
                'latitude'    => 40.692771,
                'longitude'   => -8.694399,
                'tipo'        => 'turistico',
                'imagem'      => null,
                'descricao'   => null,
            ],
            [
                'routinav_id' => 25,
                'nome'        => 'Ribeira de Ovar',
                'latitude'    => 40.84657,
                'longitude'   => -8.640979,
                'tipo'        => 'ribeira',
                'imagem'      => null,
                'descricao'   => null,
            ],
            [
                'routinav_id' => 26,
                'nome'        => 'Ribeira do Manchão',
                'latitude'    => 40.762059,
                'longitude'   => -8.659834,
                'tipo'        => 'ribeira',
                'imagem'      => null,
                'descricao'   => null,
            ],
            [
                'routinav_id' => 27,
                'nome'        => 'Tojeira',
                'latitude'    => 40.774926,
                'longitude'   => -8.658093,
                'tipo'        => 'secundario',
                'imagem'      => null,
                'descricao'   => null,
            ],
            [
                'routinav_id' => 30,
                'nome'        => 'Gafanha Aquém',
                'latitude'    => 40.610075,
                'longitude'   => -8.68372,
                'tipo'        => 'secundario',
                'imagem'      => null,
                'descricao'   => null,
            ],
            [
                'routinav_id' => 32,
                'nome'        => 'Esgueira',
                'latitude'    => 40.657104,
                'longitude'   => -8.636613,
                'tipo'        => 'secundario',
                'imagem'      => null,
                'descricao'   => null,
            ],
            [
                'routinav_id' => 79,
                'nome'        => 'Ribeira Mourão',
                'latitude'    => 40.813255,
                'longitude'   => -8.616691,
                'tipo'        => 'ribeira',
                'imagem'      => null,
                'descricao'   => null,
            ],
            [
                'routinav_id' => 82,
                'nome'        => 'Tijosa',
                'latitude'    => 40.820881,
                'longitude'   => -8.648838,
                'tipo'        => 'secundario',
                'imagem'      => null,
                'descricao'   => null,
            ],
            [
                'routinav_id' => 88,
                'nome'        => 'Ribeira da tabuada',
                'latitude'    => 40.811657,
                'longitude'   => -8.631482,
                'tipo'        => 'ribeira',
                'imagem'      => null,
                'descricao'   => null,
            ],
            [
                'routinav_id' => 91,
                'nome'        => 'Ribeira da Aldeia',
                'latitude'    => 40.801918,
                'longitude'   => -8.637565,
                'tipo'        => 'ribeira',
                'imagem'      => null,
                'descricao'   => null,
            ],
            [
                'routinav_id' => 94,
                'nome'        => 'Ribeira das Teixugueiras',
                'latitude'    => 40.792383,
                'longitude'   => -8.642208,
                'tipo'        => 'ribeira',
                'imagem'      => null,
                'descricao'   => null,
            ],
            [
                'routinav_id' => 97,
                'nome'        => 'Ribeiro do Gago',
                'latitude'    => 40.771816,
                'longitude'   => -8.649133,
                'tipo'        => 'ribeira',
                'imagem'      => null,
                'descricao'   => null,
            ],
            [
                'routinav_id' => 99,
                'nome'        => 'Cais do Moliço',
                'latitude'    => 40.540087,
                'longitude'   => -8.67462,
                'tipo'        => 'secundario',
                'imagem'      => null,
                'descricao'   => null,
            ],
            [
                'routinav_id' => 99,
                'nome'        => 'Boco',
                'latitude'    => 40.533337,
                'longitude'   => -8.666918,
                'tipo'        => 'secundario',
                'imagem'      => null,
                'descricao'   => null,
            ],
            [
                'routinav_id' => 99,
                'nome'        => 'Boco/Cais Moliço',
                'latitude'    => 40.533337,
                'longitude'   => -8.666918,
                'tipo'        => 'secundario',
                'imagem'      => null,
                'descricao'   => null,
            ],
            [
                'routinav_id' => 105,
                'nome'        => 'Ribeira de Pardelhas',
                'latitude'    => 40.739012,
                'longitude'   => -8.661473,
                'tipo'        => 'ribeira',
                'imagem'      => null,
                'descricao'   => null,
            ],
            [
                'routinav_id' => 108,
                'nome'        => 'Ilha da Gaga',
                'latitude'    => 40.71577729652845,
                'longitude'   => -8.67420908658272,
                'tipo'        => 'turistico',
                'imagem'      => null,
                'descricao'   => null,
            ],
            [
                'routinav_id' => 111,
                'nome'        => 'Moacha Norte',
                'latitude'    => 40.698378035527114,
                'longitude'   => -8.71248980738589,
                'tipo'        => 'secundario',
                'imagem'      => null,
                'descricao'   => null,
            ],
            [
                'routinav_id' => 114,
                'nome'        => 'Ilha Monte da Farinha',
                'latitude'    => 40.671255369053306,
                'longitude'   => -8.701339091915687,
                'tipo'        => 'turistico',
                'imagem'      => null,
                'descricao'   => null,
            ],
            [
                'routinav_id' => 120,
                'nome'        => 'Ilha Samos',
                'latitude'    => 40.6484985365009,
                'longitude'   => -8.689584491421035,
                'tipo'        => 'turistico',
                'imagem'      => null,
                'descricao'   => null,
            ],
            [
                'routinav_id' => 123,
                'nome'        => 'Parque da Vagueira',
                'latitude'    => 40.55030772556278,
                'longitude'   => -8.7691730895097,
                'tipo'        => 'turistico',
                'imagem'      => null,
                'descricao'   => null,
            ],
            [
                'routinav_id' => 129,
                'nome'        => 'Marégrafo da Barra',
                'latitude'    => 40.64546,
                'longitude'   => -8.74855,
                'tipo'        => 'principal',
                'imagem'      => null,
                'descricao'   => null,
            ],
            [
                'routinav_id' => 132,
                'nome'        => 'Cale da Marta',
                'latitude'    => 40.677337,
                'longitude'   => -8.688726,
                'tipo'        => 'secundario',
                'imagem'      => null,
                'descricao'   => null,
            ],
            [
                'routinav_id' => 142,
                'nome'        => 'Puxadouro',
                'latitude'    => 40.833513,
                'longitude'   => -8.623369,
                'tipo'        => 'secundario',
                'imagem'      => null,
                'descricao'   => null,
            ],
            [
                'routinav_id' => 154,
                'nome'        => 'Cova do Chegado',
                'latitude'    => 40.72566,
                'longitude'   => -8.63927,
                'tipo'        => 'secundario',
                'imagem'      => null,
                'descricao'   => null,
            ],
            [
                'routinav_id' => 166,
                'nome'        => 'PDJ Bestida (via moranzel)',
                'latitude'    => 40.760646,
                'longitude'   => -8.67927,
                'tipo'        => 'entroncamento',
                'imagem'      => null,
                'descricao'   => null,
            ],
            [
                'routinav_id' => 181,
                'nome'        => 'PDJ Torreira (por S.Jacinto)',
                'latitude'    => 40.760435,
                'longitude'   => -8.699841,
                'tipo'        => 'entroncamento',
                'imagem'      => null,
                'descricao'   => null,
            ],
            [
                'routinav_id' => 184,
                'nome'        => 'PDJ Carregal (pelo Terminal Norte)',
                'latitude'    => 40.659839,
                'longitude'   => -8.702271,
                'tipo'        => 'entroncamento',
                'imagem'      => null,
                'descricao'   => null,
            ],
            [
                'routinav_id' => 190,
                'nome'        => 'PDJ Ribeira das Teixugueiras (Varela)',
                'latitude'    => 40.790231,
                'longitude'   => -8.672809,
                'tipo'        => 'entroncamento',
                'imagem'      => null,
                'descricao'   => null,
            ],
            [
                'routinav_id' => 196,
                'nome'        => 'Ribeira das Bulhas',
                'latitude'    => 40.80603,
                'longitude'   => -8.63341,
                'tipo'        => 'ribeira',
                'imagem'      => null,
                'descricao'   => null,
            ],
            [
                'routinav_id' => null,
                'nome'        => 'Foz Antuã',
                'latitude'    => 40.723283,
                'longitude'   => -8.601644,
                'tipo'        => 'ribeira',
                'imagem'      => null,
                'descricao'   => null,
            ],
            [
                'routinav_id' => null,
                'nome'        => 'Marina Clube da Gafanha',
                'latitude'    => 40.628229,
                'longitude'   => -8.736038,
                'tipo'        => 'principal',
                'imagem'      => null,
                'descricao'   => null,
            ],
            [
                'routinav_id' => null,
                'nome'        => 'Ribeira do Nacinho',
                'latitude'    => 40.813899,
                'longitude'   => -8.626322,
                'tipo'        => 'ribeira',
                'imagem'      => null,
                'descricao'   => null,
            ],
            [
                'routinav_id' => null,
                'nome'        => 'Vista Alegre',
                'latitude'    => 40.588093,
                'longitude'   => -8.68583,
                'tipo'        => 'secundario',
                'imagem'      => null,
                'descricao'   => null,
            ],
            [
                'routinav_id' => null,
                'nome'        => 'Cais Malhada',
                'latitude'    => 40.60771,
                'longitude'   => -8.675595,
                'tipo'        => 'secundario',
                'imagem'      => null,
                'descricao'   => null,
            ],
            [
                'routinav_id' => null,
                'nome'        => 'Quinta da Tojeira',
                'latitude'    => 40.847381,
                'longitude'   => -8.645475,
                'tipo'        => 'secundario',
                'imagem'      => null,
                'descricao'   => null,
            ],
            [
                'routinav_id' => null,
                'nome'        => 'Estarreja',
                'latitude'    => 40.74917,
                'longitude'   => -8.576689,
                'tipo'        => 'secundario',
                'imagem'      => null,
                'descricao'   => null,
            ],
            [
                'routinav_id' => null,
                'nome'        => 'Cambeia',
                'latitude'    => 40.7338,
                'longitude'   => -8.62736,
                'tipo'        => 'secundario',
                'imagem'      => null,
                'descricao'   => null,
            ],
            [
                'routinav_id' => null,
                'nome'        => 'Cais do Chegado',
                'latitude'    => 40.72384,
                'longitude'   => -8.63465,
                'tipo'        => 'secundario',
                'imagem'      => null,
                'descricao'   => null,
            ],
            [
                'routinav_id' => null,
                'nome'        => 'Ribeira Nova',
                'latitude'    => 40.74708,
                'longitude'   => -8.61777,
                'tipo'        => 'ribeira',
                'imagem'      => null,
                'descricao'   => null,
            ],
            [
                'routinav_id' => null,
                'nome'        => 'PDJ Costa Nova e ANGE',
                'latitude'    => 40.61313,
                'longitude'   => -8.74731,
                'tipo'        => 'entroncamento',
                'imagem'      => null,
                'descricao'   => null,
            ],
            [
                'routinav_id' => null,
                'nome'        => 'PDJ ET Gafanha de Aquém',
                'latitude'    => 40.61136,
                'longitude'   => -8.67993,
                'tipo'        => 'entroncamento',
                'imagem'      => null,
                'descricao'   => null,
            ],
            [
                'routinav_id' => null,
                'nome'        => 'Boca da Marinha',
                'latitude'    => 40.78621,
                'longitude'   => -8.64324,
                'tipo'        => 'ribeira',
                'imagem'      => null,
                'descricao'   => null,
            ],
            [
                'routinav_id' => null,
                'nome'        => 'Ribeira do Martinho',
                'latitude'    => 40.77978,
                'longitude'   => -8.64596,
                'tipo'        => 'ribeira',
                'imagem'      => null,
                'descricao'   => null,
            ],
            [
                'routinav_id' => null,
                'nome'        => 'Marina do Egas - ANRGN',
                'latitude'    => 40.645848,
                'longitude'   => -8.699444,
                'tipo'        => 'principal',
                'imagem'      => null,
                'descricao'   => null,
            ],
        ];

        foreach ($docks as $dock) {
            Dock::create($dock);
        }

        $this->command->info('✅ ' . count($docks) . ' cais importados.');
    }
}
