<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Route;

/**
 * RouteSeeder — Rotas extraídas do documento "Curadoria de Rotas SisMAR" (Nov 2021)
 *
 * Campos populados a partir do PDF:
 *   - routinav_id   : ID numérico original do Routinav
 *   - nome          : "Partida → Chegada"
 *   - via           : variante do percurso (ex: "pela Testada", "por S. Jacinto")
 *   - descricao     : texto narrativo curado (quando disponível no PDF)
 *   - distancia_nm  : distância em milhas náuticas
 *   - gpx_file      : nome do ficheiro GPX (quando referenciado no PDF)
 *   - cais_partida  : { nome, latitude, longitude } — coordenadas do DockSeeder
 *   - cais_chegada  : { nome, latitude, longitude } — coordenadas do DockSeeder
 *   - calado_max    : calado máximo recomendado em metros
 *   - condicoes_mare: restrições de maré
 *   - recomendada   : marcada como destaque no PDF
 *   - warnings      : avisos específicos extraídos do PDF
 *
 * Campos a preencher posteriormente (Fase 5):
 *   - gpx_file      : quando os GPX forem importados para storage
 *   - simulation_data: quando a API Valida4D ou Plano B estiver implementado
 *
 * Nota sobre coordenadas: as coordenadas dos cais embebidos correspondem
 * aos valores do DockSeeder. Cais que ainda não estão no DockSeeder têm
 * coordenadas aproximadas baseadas em conhecimento geográfico da Ria de Aveiro
 * e devem ser validadas quando esses cais forem adicionados.
 */
class RouteSeeder extends Seeder
{
    // Mapa de cais com coordenadas (sincronizado com DockSeeder + novos cais do PDF)
    private array $docks = [
        'Carregal'               => ['nome' => 'Carregal',               'latitude' => 40.797500, 'longitude' => -8.668500],
        'Torreira'               => ['nome' => 'Torreira',               'latitude' => 40.760435, 'longitude' => -8.699841],
        'Bico'                   => ['nome' => 'Bico',                   'latitude' => 40.728333, 'longitude' => -8.648333],
        'Moranzel'               => ['nome' => 'Moranzel',               'latitude' => 40.710000, 'longitude' => -8.660000],
        'Parrachil'              => ['nome' => 'Parrachil',              'latitude' => 40.657000, 'longitude' => -8.700000],
        'Lavacos'                => ['nome' => 'Lavacos',                'latitude' => 40.660000, 'longitude' => -8.720000],
        'Rio Novo do Príncipe'   => ['nome' => 'Rio Novo do Príncipe',   'latitude' => 40.645000, 'longitude' => -8.680000],
        'Ilha dos Ovos'          => ['nome' => 'Ilha dos Ovos',          'latitude' => 40.680000, 'longitude' => -8.672000],
        'Amoroso'                => ['nome' => 'Amoroso',                'latitude' => 40.678000, 'longitude' => -8.670000],
        'Salreu'                 => ['nome' => 'Salreu',                 'latitude' => 40.728198, 'longitude' => -8.582032],
        'Ribeira da Aldeia'      => ['nome' => 'Ribeira da Aldeia',      'latitude' => 40.748000, 'longitude' => -8.610000],
        'Ribeira das Teixugueiras' => ['nome' => 'Ribeira das Teixugueiras', 'latitude' => 40.742000, 'longitude' => -8.618000],
        'Ponte da Varela'        => ['nome' => 'Ponte da Varela',        'latitude' => 40.764000, 'longitude' => -8.668000],
        'Tojeira'                => ['nome' => 'Tojeira',                'latitude' => 40.790000, 'longitude' => -8.640000],
        'Arieiros'               => ['nome' => 'Arieiros',               'latitude' => 40.690000, 'longitude' => -8.665000],
        'Moacha Norte'           => ['nome' => 'Moacha Norte',           'latitude' => 40.668000, 'longitude' => -8.718000],
        'Béstida'                => ['nome' => 'Béstida',                'latitude' => 40.760670, 'longitude' => -8.679062],
        // Destinos
        'ANGE'                   => ['nome' => 'ANGE',                   'latitude' => 40.613998, 'longitude' => -8.739780],
        'APARA'                  => ['nome' => 'APARA',                  'latitude' => 40.620000, 'longitude' => -8.737000],
        'Boco'                   => ['nome' => 'Boco',                   'latitude' => 40.570000, 'longitude' => -8.701000],
        'Costa Nova'             => ['nome' => 'Costa Nova',             'latitude' => 40.620000, 'longitude' => -8.748333],
        'Gafanha Aquém'          => ['nome' => 'Gafanha Aquém',          'latitude' => 40.618000, 'longitude' => -8.705000],
        'Lota'                   => ['nome' => 'Lota',                   'latitude' => 40.637000, 'longitude' => -8.657000],
        'S. Jacinto'             => ['nome' => 'S. Jacinto',             'latitude' => 40.656000, 'longitude' => -8.737000],
        'Vagueira'               => ['nome' => 'Vagueira',               'latitude' => 40.555000, 'longitude' => -8.748000],
        'Varela'                 => ['nome' => 'Varela',                 'latitude' => 40.764000, 'longitude' => -8.668000],
        'Jardim Oudinot'         => ['nome' => 'Jardim Oudinot',         'latitude' => 40.643655, 'longitude' => -8.731764],
        'Ribeira de Pardelhas'   => ['nome' => 'Ribeira de Pardelhas',   'latitude' => 40.718000, 'longitude' => -8.646000],
        'Ribeira da Aldeia (destino)' => ['nome' => 'Ribeira da Aldeia', 'latitude' => 40.748000, 'longitude' => -8.610000],
        'Baía dos Lavacos'       => ['nome' => 'Baía dos Lavacos',       'latitude' => 40.660000, 'longitude' => -8.720000],
        'Ilha do Monte Farinha'  => ['nome' => 'Ilha do Monte Farinha',  'latitude' => 40.663000, 'longitude' => -8.726000],
        'Marégrafo da Barra'     => ['nome' => 'Marégrafo da Barra',     'latitude' => 40.629000, 'longitude' => -8.750000],
        'Ponte da Barra'         => ['nome' => 'Ponte da Barra',         'latitude' => 40.629000, 'longitude' => -8.750000],
        'Moranzel (destino)'     => ['nome' => 'Moranzel',               'latitude' => 40.710000, 'longitude' => -8.660000],
        'Carregal (destino)'     => ['nome' => 'Carregal',               'latitude' => 40.797500, 'longitude' => -8.668500],
    ];

    public function run(): void
    {
        Route::truncate();

        $routes = $this->getRoutes();

        foreach ($routes as $route) {
            Route::create($route);
        }

        $this->command->info('✅ ' . count($routes) . ' rotas importadas do SisMAR.');
    }

    private function dock(string $key): array
    {
        return $this->docks[$key] ?? ['nome' => $key, 'latitude' => null, 'longitude' => null];
    }

    private function getRoutes(): array
    {
        return [

            // ============================================================
            // CAIS DE PARTIDA: CARREGAL
            // ============================================================

            [
                'routinav_id'    => 1047,
                'nome'           => 'Carregal → ANGE',
                'via'            => 'pela Testada',
                'distancia_nm'   => 15.59,
                'gpx_file'       => null,
                'cais_partida'   => $this->dock('Carregal'),
                'cais_chegada'   => $this->dock('ANGE'),
                'calado_max'     => 1.0,
                'condicoes_mare' => 'favoravel',
                'recomendada'    => false,
                'rota_direta'    => true,
                'warnings'       => ['Segmento final substituído — rota original passava por cima de sequeiro na chegada à ANGE'],
            ],
            [
                'routinav_id'    => 1068,
                'nome'           => 'Carregal → ANGE',
                'via'            => 'pela Marinha do Sal e Veia da Testada',
                'descricao'      => 'Rota muito interessante e, simultaneamente, muito técnica, pois só poderá ser realizada em condições de estofo da maré, e com barcos de baixo calado, especialmente no canalete da Marina do Sal e na zona entre o Vela Areínho e o Carregal. Em condições ideais, navega-se tranquilamente pelo percurso indicado, passando-se pelo Areinho, Torrão do Lameiro e entrando-se no canalete da Marinha do Sal para se atingir o Canal de Ovar, já mais a Sul e, logo a seguir, a Ponte da Varela. Depois da Torreira navega-se numa diagonal em direção ao canal de entrada para a Bacia do Laranjo, virando-se depois para Nascente. Depois de passar o Bico da Murtosa e o Cais do Chegado entra-se para a sinuosa Veia da Testada até se desembocar na Cale do Parrachil. Segue-se para SO pela Cale do Espinheiro, contornando-se a seguir o molhe da Praia de Lavacos, passando-se por São Jacinto, entrando no canalete do Forte da Barra, passando-se pela Ponte da Barra e pela Costa Nova e, finalmente, chegando à ANGE.',
                'distancia_nm'   => 19.03,
                'gpx_file'       => null,
                'cais_partida'   => $this->dock('Carregal'),
                'cais_chegada'   => $this->dock('ANGE'),
                'calado_max'     => 0.3,
                'condicoes_mare' => 'estofo',
                'recomendada'    => true,
                'rota_direta'    => false,
                'warnings'       => ['Outliers perto do Torrão do Lameiro (0,8 a 0,3m) a corrigir'],
            ],
            [
                'routinav_id'    => 162,
                'nome'           => 'Carregal → APARA',
                'via'            => 'por S. Jacinto',
                'distancia_nm'   => null,
                'gpx_file'       => null,
                'cais_partida'   => $this->dock('Carregal'),
                'cais_chegada'   => $this->dock('APARA'),
                'calado_max'     => 1.0,
                'condicoes_mare' => 'favoravel',
                'recomendada'    => false,
                'rota_direta'    => true,
                'warnings'       => ['A Norte do bico do Moranzel a rota foi adquirida junto à margem Poente e passa por cima do sequeiro existente'],
            ],
            [
                'routinav_id'    => 1098,
                'nome'           => 'Carregal → APARA',
                'via'            => 'pela Marinha do Sal e Veia da Testada',
                'descricao'      => 'Rota muito interessante e, simultaneamente, muito técnica, pois só poderá ser realizada em condições de estofo da maré, e com barcos de baixo calado, especialmente no canalete da Marina do Sal e na zona entre o Vela Areínho e o Carregal. Em condições ideais, navega-se tranquilamente pelo percurso indicado, passando-se pelo Areinho, Torrão do Lameiro e entrando-se no canalete da Marinha do Sal para se atingir o Canal de Ovar, já mais a Sul e, logo a seguir, a Ponte da Varela. Depois da Torreira navega-se numa diagonal em direção ao canal de entrada para a Bacia do Laranjo, virando-se depois para Nascente. Depois de passar o Bico da Murtosa e o Cais do Chegado entra-se para a sinuosa Veia da Testada até se desembocar na Cale do Parrachil. Segue-se para SO pela Cale do Espinheiro, contornando a seguir o molhe da Praia de Lavacos, passando-se por São Jacinto, entrando no canalete do Forte da Barra e, finalmente, chegando à APARA.',
                'distancia_nm'   => null,
                'gpx_file'       => null,
                'cais_partida'   => $this->dock('Carregal'),
                'cais_chegada'   => $this->dock('APARA'),
                'calado_max'     => 0.3,
                'condicoes_mare' => 'estofo',
                'recomendada'    => false,
                'rota_direta'    => false,
                'warnings'       => ['Outliers perto do Torrão do Lameiro (0,8 a 0,3m) a corrigir'],
            ],
            [
                'routinav_id'    => 111,
                'nome'           => 'Carregal → Boco',
                'via'            => 'por S. Jacinto',
                'descricao'      => 'Rota muito interessante e, simultaneamente, muito técnica, pois só poderá ser realizada em condições de estofo da maré e com barcos de baixo calado.',
                'distancia_nm'   => 20.41,
                'gpx_file'       => null,
                'cais_partida'   => $this->dock('Carregal'),
                'cais_chegada'   => $this->dock('Boco'),
                'calado_max'     => 0.3,
                'condicoes_mare' => 'estofo',
                'recomendada'    => true,
                'rota_direta'    => true,
                'warnings'       => ['Rota TOP — simular com calado 0,3m; partir antes da PM para chegar em estofo'],
            ],
            [
                'routinav_id'    => 1026,
                'nome'           => 'Carregal → Boco',
                'via'            => 'pela Testada',
                'descricao'      => 'Rota muito interessante e, simultaneamente, muito técnica, pois só poderá ser realizada em condições de estofo da maré e com barcos de baixo calado.',
                'distancia_nm'   => 22.42,
                'gpx_file'       => null,
                'cais_partida'   => $this->dock('Carregal'),
                'cais_chegada'   => $this->dock('Boco'),
                'calado_max'     => 0.3,
                'condicoes_mare' => 'estofo',
                'recomendada'    => false,
                'rota_direta'    => false,
                'warnings'       => ['Outliers ao pé do Torrão de Lameiro a eliminar'],
            ],
            [
                'routinav_id'    => 252,
                'nome'           => 'Carregal → Costa Nova',
                'via'            => 'por S. Jacinto',
                'distancia_nm'   => 14.05,
                'gpx_file'       => null,
                'cais_partida'   => $this->dock('Carregal'),
                'cais_chegada'   => $this->dock('Costa Nova'),
                'calado_max'     => 1.0,
                'condicoes_mare' => 'favoravel',
                'recomendada'    => false,
                'rota_direta'    => true,
                'descricao'      => 'Rota complexa pois passa por cima de diversos sequeiros, mas realizável com barcos com calado de 1 metro desde que se escolha corretamente a hora de partida e a velocidade média a manter.',
                'warnings'       => [],
            ],
            [
                'routinav_id'    => 480,
                'nome'           => 'Carregal → Costa Nova',
                'via'            => 'à vela',
                'distancia_nm'   => 17.88,
                'gpx_file'       => null,
                'cais_partida'   => $this->dock('Carregal'),
                'cais_chegada'   => $this->dock('Costa Nova'),
                'calado_max'     => 0.5,
                'condicoes_mare' => 'favoravel',
                'recomendada'    => false,
                'rota_direta'    => true,
                'descricao'      => 'Rota adquirida à bolina que poderá ser útil em situações de se navegar à vela com vento sul. Complexa pois passa por cima de diversos sequeiros, e realizável com barcos com calado de 0,5 metros desde que se escolha corretamente a hora de partida e a velocidade média a manter.',
                'warnings'       => [],
            ],
            [
                'routinav_id'    => 108,
                'nome'           => 'Carregal → Gafanha Aquém',
                'via'            => 'por S. Jacinto',
                'distancia_nm'   => 15.58,
                'gpx_file'       => null,
                'cais_partida'   => $this->dock('Carregal'),
                'cais_chegada'   => $this->dock('Gafanha Aquém'),
                'calado_max'     => 1.0,
                'condicoes_mare' => 'favoravel',
                'recomendada'    => true,
                'rota_direta'    => true,
                'descricao'      => 'Rota realizável com barcos até 1 metro de calado desde que se escolha bem a hora de partida e a velocidade média a manter.',
                'warnings'       => ['Outlier de 0,8m a Sul da marina da Torreira corrigido'],
            ],
            [
                'routinav_id'    => 1272,
                'nome'           => 'Carregal → Gafanha Aquém',
                'via'            => 'pela Marinha do Sal',
                'distancia_nm'   => 18.25,
                'gpx_file'       => null,
                'cais_partida'   => $this->dock('Carregal'),
                'cais_chegada'   => $this->dock('Gafanha Aquém'),
                'calado_max'     => 0.3,
                'condicoes_mare' => 'estofo',
                'recomendada'    => false,
                'rota_direta'    => false,
                'descricao'      => 'A rota passa pelo canalete, pouco profundo, da Marinha do Sal e pela Veia da Testada, mas é realizável com barcos com calado de 0,3 metros desde que se escolha corretamente a hora de partida e a velocidade média a manter.',
                'warnings'       => ['Outliers ao pé do Torrão de Lameiro a eliminar'],
            ],
            [
                'routinav_id'    => 450,
                'nome'           => 'Carregal → Ilha dos Ovos',
                'via'            => 'pela Marinha do Sal',
                'distancia_nm'   => 13.91,
                'gpx_file'       => null,
                'cais_partida'   => $this->dock('Carregal'),
                'cais_chegada'   => $this->dock('Ilha dos Ovos'),
                'calado_max'     => 0.3,
                'condicoes_mare' => 'estofo',
                'recomendada'    => false,
                'rota_direta'    => false,
                'descricao'      => 'Rota complexa pois passa pelos canaletes, pouco profundos, da Marinha do Sal e da entrada para o Amoroso, mas realizável com barcos com calado de 0,3 metros desde que se escolha corretamente a hora de partida e a velocidade média a manter.',
                'warnings'       => ['Outliers entre o Carregal e a entrada para a Marinha do Sal corrigidos'],
            ],
            [
                'routinav_id'    => 141,
                'nome'           => 'Carregal → Lota',
                'via'            => 'por S. Jacinto e Cale dos Bolhões',
                'distancia_nm'   => null,
                'gpx_file'       => null,
                'cais_partida'   => $this->dock('Carregal'),
                'cais_chegada'   => $this->dock('Lota'),
                'calado_max'     => 1.0,
                'condicoes_mare' => 'favoravel',
                'recomendada'    => false,
                'rota_direta'    => true,
                'descricao'      => 'Rota fácil e realizável em várias condições de maré (excetuando na zona à saída do Carregal por não ter sido adquirida sobre o canal) com barcos até 1 metro de calado.',
                'warnings'       => ['Zona a partir de 40.679039, -8.653816 sem dados de maré (cor roxa)'],
            ],
            [
                'routinav_id'    => 888,
                'nome'           => 'Carregal → Lota',
                'via'            => 'pela Veia da Testada e Cale dos Bolhões',
                'distancia_nm'   => null,
                'gpx_file'       => null,
                'cais_partida'   => $this->dock('Carregal'),
                'cais_chegada'   => $this->dock('Lota'),
                'calado_max'     => 1.0,
                'condicoes_mare' => 'favoravel',
                'recomendada'    => false,
                'rota_direta'    => false,
                'descricao'      => 'Rota realizável em algumas condições de maré (excetuando na zona à saída do Carregal por não ter sido adquirida sobre o canal) com barcos até 1 metro de calado.',
                'warnings'       => [],
            ],
            [
                'routinav_id'    => 135,
                'nome'           => 'Carregal → Moranzel',
                'via'            => null,
                'distancia_nm'   => 8.68,
                'gpx_file'       => null,
                'cais_partida'   => $this->dock('Carregal'),
                'cais_chegada'   => $this->dock('Moranzel'),
                'calado_max'     => 1.0,
                'condicoes_mare' => 'favoravel',
                'recomendada'    => false,
                'rota_direta'    => true,
                'descricao'      => 'Rota realizável em várias condições de maré (excetuando na zona em frente ao Vela Areinho por não ter sido adquirida sobre o canal) com barcos até 1 metro de calado.',
                'warnings'       => [],
            ],
            [
                'routinav_id'    => 1125,
                'nome'           => 'Carregal → Moranzel',
                'via'            => 'com passagem na Ribeira das Teixugueiras',
                'distancia_nm'   => 10.82,
                'gpx_file'       => null,
                'cais_partida'   => $this->dock('Carregal'),
                'cais_chegada'   => $this->dock('Moranzel'),
                'calado_max'     => 1.0,
                'condicoes_mare' => 'favoravel',
                'recomendada'    => false,
                'rota_direta'    => false,
                'descricao'      => 'Rota realizável em várias condições de maré com barcos até 1 metro de calado. Com passagem na Ribeira das Teixugueiras.',
                'warnings'       => [],
            ],
            [
                'routinav_id'    => 1191,
                'nome'           => 'Carregal → Ribeira da Aldeia',
                'via'            => 'pela Marinha do Sal',
                'distancia_nm'   => 4.55,
                'gpx_file'       => null,
                'cais_partida'   => $this->dock('Carregal'),
                'cais_chegada'   => $this->dock('Ribeira da Aldeia'),
                'calado_max'     => 1.0,
                'condicoes_mare' => 'estofo',
                'recomendada'    => true,
                'rota_direta'    => false,
                'descricao'      => 'Rota muito interessante e, simultaneamente, técnica, mas que pode ser realizada com barcos até 1 metro de calado desde que em condições de estofo da maré. Partindo-se da Marina do Carregal, navega-se para Sul até ao Covelo, onde se pode guinar para Bombordo e entrar no canalete da Marinha do Sal (que deverá ser navegado com muita atenção). Depois de sair do canalete, atravessa-se o ramo nascente do canal de Ovar e entra-se no Esteiro da Aldeia até se chegar ao respetivo cais.',
                'warnings'       => [],
            ],
            [
                'routinav_id'    => 1206,
                'nome'           => 'Carregal → Ribeira da Aldeia',
                'via'            => 'pelo Esteiro da Amieira',
                'distancia_nm'   => 5.63,
                'gpx_file'       => null,
                'cais_partida'   => $this->dock('Carregal'),
                'cais_chegada'   => $this->dock('Ribeira da Aldeia'),
                'calado_max'     => 1.0,
                'condicoes_mare' => 'favoravel',
                'recomendada'    => true,
                'rota_direta'    => false,
                'descricao'      => 'Rota muito interessante e, simultaneamente, técnica, mas que pode ser realizada com barcos até 1 metro de calado em várias condições da maré. Partindo-se da Marina do Carregal, navega-se para Sul até ao Sul do Cabo da Marina (próximo da Ponte da Varela), onde se pode guinar para Nordeste e, depois, para Estibordo para entrar no Esteiro da Amieira. Pouco depois guina-se para Bombordo para entrar no estreito canalete que liga ao Cais da Ribeira da Aldeia.',
                'warnings'       => [],
            ],
            [
                'routinav_id'    => 138,
                'nome'           => 'Carregal → S. Jacinto',
                'via'            => null,
                'distancia_nm'   => 11.94,
                'gpx_file'       => '10_CO_1_Carregal__ET_3_SJacinto_cais.gpx',
                'cais_partida'   => $this->dock('Carregal'),
                'cais_chegada'   => $this->dock('S. Jacinto'),
                'calado_max'     => 1.0,
                'condicoes_mare' => 'favoravel',
                'recomendada'    => false,
                'rota_direta'    => true,
                'descricao'      => 'Rota de fácil navegação e praticável com várias condições de maré (excetuando na zona em frente ao Vela Areinho por não ter sido adquirida sobre o canal).',
                'warnings'       => [],
            ],
            [
                'routinav_id'    => 105,
                'nome'           => 'Carregal → Torreira',
                'via'            => null,
                'distancia_nm'   => 6.16,
                'gpx_file'       => null,
                'cais_partida'   => $this->dock('Carregal'),
                'cais_chegada'   => $this->dock('Torreira'),
                'calado_max'     => 1.0,
                'condicoes_mare' => 'favoravel',
                'recomendada'    => false,
                'rota_direta'    => true,
                'descricao'      => 'Rota de fácil navegação em várias condições de maré (excetuando a zona a Norte do Areinho e a zona na margem Nascente em frente às Quintas do Sul por não terem sido adquiridas sobre o canal).',
                'warnings'       => [],
            ],
            [
                'routinav_id'    => 1011,
                'nome'           => 'Carregal → Torreira',
                'via'            => 'pela Marinha do Sal',
                'distancia_nm'   => 7.25,
                'gpx_file'       => null,
                'cais_partida'   => $this->dock('Carregal'),
                'cais_chegada'   => $this->dock('Torreira'),
                'calado_max'     => 0.3,
                'condicoes_mare' => 'estofo',
                'recomendada'    => false,
                'rota_direta'    => false,
                'descricao'      => 'Pela Marinha do Sal – para barcos de calado <0,3m.',
                'warnings'       => [],
            ],
            [
                'routinav_id'    => 99,
                'nome'           => 'Carregal → Vagueira',
                'via'            => 'por São Jacinto',
                'distancia_nm'   => 18.09,
                'gpx_file'       => null,
                'cais_partida'   => $this->dock('Carregal'),
                'cais_chegada'   => $this->dock('Vagueira'),
                'calado_max'     => 1.0,
                'condicoes_mare' => 'favoravel',
                'recomendada'    => false,
                'rota_direta'    => true,
                'descricao'      => 'Rota extensa e, como tal, se navegada a baixa velocidade é condicionada pela dinâmica da maré em algumas zonas, como por exemplo a Norte do Areinho (onde não foi adquirida sobre o canal).',
                'warnings'       => [],
            ],
            [
                'routinav_id'    => 144,
                'nome'           => 'Carregal → Vagueira',
                'via'            => 'pela Marinha do Sal e Veia da Testada',
                'distancia_nm'   => null,
                'gpx_file'       => null,
                'cais_partida'   => $this->dock('Carregal'),
                'cais_chegada'   => $this->dock('Vagueira'),
                'calado_max'     => 0.3,
                'condicoes_mare' => 'estofo',
                'recomendada'    => false,
                'rota_direta'    => false,
                'descricao'      => 'Pela Marinha do Sal e Veia da Testada.',
                'warnings'       => [],
            ],
            [
                'routinav_id'    => 16,
                'nome'           => 'Carregal → Varela',
                'via'            => null,
                'distancia_nm'   => 3.70,
                'gpx_file'       => null,
                'cais_partida'   => $this->dock('Carregal'),
                'cais_chegada'   => $this->dock('Varela'),
                'calado_max'     => 1.0,
                'condicoes_mare' => 'favoravel',
                'recomendada'    => false,
                'rota_direta'    => true,
                'warnings'       => [],
            ],
            [
                'routinav_id'    => 1014,
                'nome'           => 'Carregal → Varela',
                'via'            => 'pela Marinha do Sal',
                'distancia_nm'   => 4.94,
                'gpx_file'       => null,
                'cais_partida'   => $this->dock('Carregal'),
                'cais_chegada'   => $this->dock('Varela'),
                'calado_max'     => 0.3,
                'condicoes_mare' => 'estofo',
                'recomendada'    => false,
                'rota_direta'    => false,
                'descricao'      => 'Rota muito interessante e, simultaneamente, muito técnica, pois só poderá ser realizada em condições de estofo da maré, e com barcos de baixo calado, especialmente no canalete da Marina do Sal e na zona em frente ao Parque da Azureira, onde foi adquirida fora do canal.',
                'warnings'       => [],
            ],

            // ============================================================
            // CAIS DE PARTIDA: RIBEIRA DA ALDEIA
            // ============================================================

            [
                'routinav_id'    => 1194,
                'nome'           => 'Ribeira da Aldeia → Carregal',
                'via'            => null,
                'distancia_nm'   => null,
                'gpx_file'       => null,
                'cais_partida'   => $this->dock('Ribeira da Aldeia'),
                'cais_chegada'   => $this->dock('Carregal (destino)'),
                'calado_max'     => 1.0,
                'condicoes_mare' => 'favoravel',
                'recomendada'    => false,
                'rota_direta'    => true,
                'warnings'       => [],
            ],
            [
                'routinav_id'    => 1203,
                'nome'           => 'Ribeira da Aldeia → Carregal',
                'via'            => null,
                'distancia_nm'   => 5.63,
                'gpx_file'       => null,
                'cais_partida'   => $this->dock('Ribeira da Aldeia'),
                'cais_chegada'   => $this->dock('Carregal (destino)'),
                'calado_max'     => 1.0,
                'condicoes_mare' => 'favoravel',
                'recomendada'    => false,
                'rota_direta'    => true,
                'warnings'       => [],
            ],
            [
                'routinav_id'    => 1209,
                'nome'           => 'Ribeira da Aldeia → Ribeira das Teixugueiras',
                'via'            => null,
                'distancia_nm'   => 3.76,
                'gpx_file'       => null,
                'cais_partida'   => $this->dock('Ribeira da Aldeia'),
                'cais_chegada'   => $this->dock('Ribeira das Teixugueiras'),
                'calado_max'     => 1.0,
                'condicoes_mare' => 'favoravel',
                'recomendada'    => false,
                'rota_direta'    => true,
                'descricao'      => 'Rota que pode ser realizada com barcos até 1 metro de calado em várias condições da maré. Partindo-se do Cais da Ribeira da Aldeia, navega-se pelo estreito canalete que liga ao esteiro da Amieira. À saída do esteiro guina-se para Sudoeste até ao Sul do Cabo da Marinha do Sal (próximo da Ponte da Varela), onde se pode conectar a outro percurso realizado desde aí até ao Esteiro das Teixugueiras e à respetiva Ribeira.',
                'warnings'       => ['Outlier de 0,8m no Esteiro das Teixugueiras a eliminar'],
            ],
            [
                'routinav_id'    => 1215,
                'nome'           => 'Ribeira da Aldeia → Torreira',
                'via'            => null,
                'distancia_nm'   => 4.43,
                'gpx_file'       => null,
                'cais_partida'   => $this->dock('Ribeira da Aldeia'),
                'cais_chegada'   => $this->dock('Torreira'),
                'calado_max'     => 1.0,
                'condicoes_mare' => 'favoravel',
                'recomendada'    => false,
                'rota_direta'    => true,
                'warnings'       => [],
            ],

            // ============================================================
            // CAIS DE PARTIDA: RIBEIRA DAS TEIXUGUEIRAS
            // ============================================================

            [
                'routinav_id'    => 1254,
                'nome'           => 'Ribeira das Teixugueiras → Bico',
                'via'            => null,
                'distancia_nm'   => null,
                'gpx_file'       => null,
                'cais_partida'   => $this->dock('Ribeira das Teixugueiras'),
                'cais_chegada'   => $this->dock('Bico'),
                'calado_max'     => 1.0,
                'condicoes_mare' => 'favoravel',
                'recomendada'    => false,
                'rota_direta'    => true,
                'warnings'       => [],
            ],
            [
                'routinav_id'    => 1131,
                'nome'           => 'Ribeira das Teixugueiras → Moranzel',
                'via'            => null,
                'distancia_nm'   => 5.70,
                'gpx_file'       => null,
                'cais_partida'   => $this->dock('Ribeira das Teixugueiras'),
                'cais_chegada'   => $this->dock('Moranzel'),
                'calado_max'     => 1.0,
                'condicoes_mare' => 'favoravel',
                'recomendada'    => false,
                'rota_direta'    => true,
                'descricao'      => 'Rota relativamente fácil e praticável com barcos de 1 metro de calado em praticamente todas as condições de maré. Partindo-se da Ribeira das Teixugueiras, navega-se pelo respetivo esteiro até à Ponte da Varela. Depois continua-se a seguir o trajeto indicado, passando-se pelas Quintas do Sul e pela Torreira para, finalmente, se chegar ao Bico do Moranzel.',
                'warnings'       => ['Outlier de 0,8m no Esteiro das Teixugueiras a corrigir'],
            ],
            [
                'routinav_id'    => 1212,
                'nome'           => 'Ribeira das Teixugueiras → Ribeira da Aldeia',
                'via'            => null,
                'distancia_nm'   => 5.70,
                'gpx_file'       => null,
                'cais_partida'   => $this->dock('Ribeira das Teixugueiras'),
                'cais_chegada'   => $this->dock('Ribeira da Aldeia'),
                'calado_max'     => 1.0,
                'condicoes_mare' => 'favoravel',
                'recomendada'    => false,
                'rota_direta'    => true,
                'descricao'      => 'Rota que pode ser realizada com barcos até 1 metro de calado em várias condições da maré. Partindo-se do Cais da Ribeira das Teixugueiras navega-se pelo respetivo Esteiro até à zona a Norte da Ponte da Varela. Aí pode-se conectar a outro percurso realizado para o esteiro da Amieira, a partir do qual, guindando-se para Bombordo se alcança o canalete que leva até à Ribeira da Aldeia.',
                'warnings'       => ['Outlier de 0,9m no Esteiro das Teixugueiras a eliminar'],
            ],

            // ============================================================
            // CAIS DE PARTIDA: TOJEIRA
            // ============================================================

            [
                'routinav_id'    => 318,
                'nome'           => 'Tojeira → ANGE',
                'via'            => 'por São Jacinto',
                'distancia_nm'   => 10.73,
                'gpx_file'       => '99_16_Tojeira__Testada__CM_4_ANGE.gpx',
                'cais_partida'   => $this->dock('Tojeira'),
                'cais_chegada'   => $this->dock('ANGE'),
                'calado_max'     => 1.0,
                'condicoes_mare' => 'favoravel',
                'recomendada'    => false,
                'rota_direta'    => true,
                'warnings'       => [],
            ],

            // ============================================================
            // CAIS DE PARTIDA: PONTE DA VARELA
            // ============================================================

            [
                'routinav_id'    => 951,
                'nome'           => 'Ponte da Varela → ANGE',
                'via'            => 'pela Testada',
                'distancia_nm'   => null,
                'gpx_file'       => null,
                'cais_partida'   => $this->dock('Ponte da Varela'),
                'cais_chegada'   => $this->dock('ANGE'),
                'calado_max'     => 1.0,
                'condicoes_mare' => 'favoravel',
                'recomendada'    => false,
                'rota_direta'    => false,
                'warnings'       => ['Valores de Zr incorretos — muitos 15m e distância em milhas muito pequena'],
            ],
            [
                'routinav_id'    => 1083,
                'nome'           => 'Ponte da Varela → ANGE',
                'via'            => 'pela Testada',
                'distancia_nm'   => null,
                'gpx_file'       => '100_ET_1_Varela__Testada__CM_4_ANGE.gpx',
                'cais_partida'   => $this->dock('Ponte da Varela'),
                'cais_chegada'   => $this->dock('ANGE'),
                'calado_max'     => 1.0,
                'condicoes_mare' => 'favoravel',
                'recomendada'    => false,
                'rota_direta'    => false,
                'warnings'       => ['Vários pontos de possível encalhe se não estiver em PM'],
            ],

            // ============================================================
            // CAIS DE PARTIDA: TORREIRA
            // ============================================================

            [
                'routinav_id'    => 174,
                'nome'           => 'Torreira → ANGE',
                'via'            => 'por São Jacinto',
                'distancia_nm'   => 9.26,
                'gpx_file'       => null,
                'cais_partida'   => $this->dock('Torreira'),
                'cais_chegada'   => $this->dock('ANGE'),
                'calado_max'     => 1.0,
                'condicoes_mare' => 'favoravel',
                'recomendada'    => false,
                'rota_direta'    => true,
                'descricao'      => 'Rota relativamente fácil de navegar, mas que terá que ser feita em condições favoráveis de maré nomeadamente na área a Norte do bico do Moranzel. Nessa zona, a rota foi adquirida muito junto à margem Poente e, como tal, passa por cima do sequeiro existente.',
                'warnings'       => [],
            ],
            [
                'routinav_id'    => 1059,
                'nome'           => 'Torreira → ANGE',
                'via'            => null,
                'distancia_nm'   => 9.15,
                'gpx_file'       => null,
                'cais_partida'   => $this->dock('Torreira'),
                'cais_chegada'   => $this->dock('ANGE'),
                'calado_max'     => 1.0,
                'condicoes_mare' => 'favoravel',
                'recomendada'    => false,
                'rota_direta'    => true,
                'descricao'      => 'Rota relativamente fácil de navegar, mas que, sobre os cabeços do Travessadouro e do Cão (abaixo do Moranzel) e em frente ao Navio Santo André, terá que ser feita em condições favoráveis de maré.',
                'warnings'       => [],
            ],
            [
                'routinav_id'    => 165,
                'nome'           => 'Torreira → APARA',
                'via'            => null,
                'distancia_nm'   => 7.65,
                'gpx_file'       => null,
                'cais_partida'   => $this->dock('Torreira'),
                'cais_chegada'   => $this->dock('APARA'),
                'calado_max'     => 1.0,
                'condicoes_mare' => 'favoravel',
                'recomendada'    => false,
                'rota_direta'    => true,
                'descricao'      => 'Rota relativamente fácil de navegar, mas que, sobre as áreas a Norte do bico do Moranzel, da antiga balança (ao pé de São Jacinto) e em frente ao Navio Santo André, terá que ser feita em condições favoráveis de maré.',
                'warnings'       => [],
            ],
            [
                'routinav_id'    => 441,
                'nome'           => 'Torreira → Arieiros',
                'via'            => null,
                'distancia_nm'   => 3.87,
                'gpx_file'       => null,
                'cais_partida'   => $this->dock('Torreira'),
                'cais_chegada'   => $this->dock('Arieiros'),
                'calado_max'     => 1.0,
                'condicoes_mare' => 'favoravel',
                'recomendada'    => false,
                'rota_direta'    => true,
                'descricao'      => 'Rota relativamente fácil de navegar, mas que terá que ser feita em condições favoráveis de maré, especialmente na ligação entre o Moranzel e o Bico da Murtosa e na Veia da Testada.',
                'warnings'       => [],
            ],
            [
                'routinav_id'    => 459,
                'nome'           => 'Torreira → Bico',
                'via'            => null,
                'distancia_nm'   => 2.71,
                'gpx_file'       => null,
                'cais_partida'   => $this->dock('Torreira'),
                'cais_chegada'   => $this->dock('Bico'),
                'calado_max'     => 1.0,
                'condicoes_mare' => 'favoravel',
                'recomendada'    => false,
                'rota_direta'    => true,
                'descricao'      => 'Rota relativamente fácil de navegar, mas que terá que ser feita em condições favoráveis de maré, especialmente na ligação entre o Moranzel e o Bico da Murtosa.',
                'warnings'       => [],
            ],
            [
                'routinav_id'    => 765,
                'nome'           => 'Torreira → Boco',
                'via'            => 'por São Jacinto',
                'distancia_nm'   => 13.62,
                'gpx_file'       => null,
                'cais_partida'   => $this->dock('Torreira'),
                'cais_chegada'   => $this->dock('Boco'),
                'calado_max'     => 0.3,
                'condicoes_mare' => 'estofo',
                'recomendada'    => false,
                'rota_direta'    => true,
                'descricao'      => 'Rota muito técnica pois é necessário sair cerca de 2 horas (navegando a 5 nós) antes da praia-mar para chegar ao destino no estofo da maré. Para barcos de calado <0,3m.',
                'warnings'       => [],
            ],
            [
                'routinav_id'    => 771,
                'nome'           => 'Torreira → Boco',
                'via'            => 'por São Jacinto (pela Testada)',
                'distancia_nm'   => 15.78,
                'gpx_file'       => null,
                'cais_partida'   => $this->dock('Torreira'),
                'cais_chegada'   => $this->dock('Boco'),
                'calado_max'     => 0.3,
                'condicoes_mare' => 'estofo',
                'recomendada'    => true,
                'rota_direta'    => false,
                'descricao'      => 'Rota muito interessante e, simultaneamente, muito técnica, pois só poderá ser realizada em condições de estofo da maré e com barcos de baixo calado. Partindo-se da Torreira navega-se numa diagonal em direção ao canal de entrada para a Bacia do Laranjo, virando-se depois para Nascente. Depois de passar o Bico da Murtosa e o Cais do Chegado entra-se para a sinuosa Veia da Testada até se desembocar na Cale do Parrachil. Segue-se para SO pela Cale do Espinheiro até ao Terminal Químico, guinando depois para SE e navegando pela Cale do Sama até à ponte da Friopesca. Continua-se, depois, pelo Rio Boco para se passar primeiro na ponte de Ílhavo, depois na ponte da Vista-Alegre e, ainda, na ponte da N109. Já muito perto do Cais do Moliço, no fim da rota, passa-se, ainda, por uma velha ponte e pela ponte da N333.',
                'warnings'       => [],
            ],
            [
                'routinav_id'    => 336,
                'nome'           => 'Torreira → Carregal',
                'via'            => 'à vela',
                'distancia_nm'   => 6.98,
                'gpx_file'       => null,
                'cais_partida'   => $this->dock('Torreira'),
                'cais_chegada'   => $this->dock('Carregal (destino)'),
                'calado_max'     => 1.0,
                'condicoes_mare' => 'favoravel',
                'recomendada'    => false,
                'rota_direta'    => true,
                'descricao'      => 'Rota adquirida à vela e relativamente fácil de navegar, mas que terá que ser feita em condições favoráveis de maré em várias zonas do percurso.',
                'warnings'       => [],
            ],
            [
                'routinav_id'    => 1287,
                'nome'           => 'Torreira → Carregal',
                'via'            => 'pela Marinha do Sal',
                'distancia_nm'   => 7.22,
                'gpx_file'       => null,
                'cais_partida'   => $this->dock('Torreira'),
                'cais_chegada'   => $this->dock('Carregal (destino)'),
                'calado_max'     => 0.3,
                'condicoes_mare' => 'estofo',
                'recomendada'    => true,
                'rota_direta'    => false,
                'descricao'      => 'Rota muito interessante e, simultaneamente, muito técnica, pois só poderá ser realizada em condições de estofo da maré, e com barcos de baixo calado, especialmente no canalete da Marina do Sal e na zona entre o Vela Areínho e o Carregal. Em condições ideais, navega-se tranquilamente, pelo percurso indicado, desde a Torreira até à Ponte da Varela. A seguir, navega-se para dentro da Marinha do Sal para se atingir o Canal de Ovar já mais a Norte, passando-se pelo Torrão do Lameiro, Areinho e, finalmente, chegando-se ao Carregal.',
                'warnings'       => [],
            ],
            [
                'routinav_id'    => 366,
                'nome'           => 'Torreira → Costa Nova',
                'via'            => 'por São Jacinto',
                'distancia_nm'   => 9.09,
                'gpx_file'       => null,
                'cais_partida'   => $this->dock('Torreira'),
                'cais_chegada'   => $this->dock('Costa Nova'),
                'calado_max'     => 1.0,
                'condicoes_mare' => 'favoravel',
                'recomendada'    => false,
                'rota_direta'    => true,
                'descricao'      => 'Rota relativamente fácil de navegar, mas que terá que ser feita em condições favoráveis de maré, especialmente à saída da Torreira, a Norte do bico do Moranzel e a sul do Cabeço do Travessadouro.',
                'warnings'       => [],
            ],
            [
                'routinav_id'    => 603,
                'nome'           => 'Torreira → Gafanha Aquém',
                'via'            => 'por São Jacinto',
                'distancia_nm'   => 9.34,
                'gpx_file'       => null,
                'cais_partida'   => $this->dock('Torreira'),
                'cais_chegada'   => $this->dock('Gafanha Aquém'),
                'calado_max'     => 1.0,
                'condicoes_mare' => 'favoravel',
                'recomendada'    => false,
                'rota_direta'    => true,
                'descricao'      => 'Rota relativamente fácil de navegar, mas que terá que ser feita em condições favoráveis de maré, especialmente sobre as áreas a Norte do bico do Moranzel e após a ponte da Friopesca.',
                'warnings'       => [],
            ],
            [
                'routinav_id'    => 1146,
                'nome'           => 'Torreira → Baía dos Lavacos',
                'via'            => null,
                'distancia_nm'   => 6.68,
                'gpx_file'       => null,
                'cais_partida'   => $this->dock('Torreira'),
                'cais_chegada'   => $this->dock('Baía dos Lavacos'),
                'calado_max'     => 1.0,
                'condicoes_mare' => 'favoravel',
                'recomendada'    => false,
                'rota_direta'    => true,
                'descricao'      => 'Rota relativamente fácil de navegar, mas que terá que ser feita em condições favoráveis de maré, especialmente sobre as áreas a Norte do bico do Moranzel, da antiga balança (ao pé de São Jacinto) e a parte de dentro do molhe separador (do Canal de São Jacinto e do Canal da Vila) até à Praia de Lavacos.',
                'warnings'       => [],
            ],

            // ============================================================
            // CAIS DE PARTIDA: CAIS DO BICO
            // ============================================================

            [
                'routinav_id'    => 954,
                'nome'           => 'Bico → ANGE',
                'via'            => 'pela Testada',
                'distancia_nm'   => 9.37,
                'gpx_file'       => '105_BL3_CaisBico__CM4_ANGE.gpx',
                'cais_partida'   => $this->dock('Bico'),
                'cais_chegada'   => $this->dock('ANGE'),
                'calado_max'     => 1.0,
                'condicoes_mare' => 'favoravel',
                'recomendada'    => false,
                'rota_direta'    => false,
                'warnings'       => [],
            ],
            [
                'routinav_id'    => 81,
                'nome'           => 'Bico → APARA',
                'via'            => 'por S. Jacinto',
                'distancia_nm'   => 7.19,
                'gpx_file'       => null,
                'cais_partida'   => $this->dock('Bico'),
                'cais_chegada'   => $this->dock('APARA'),
                'calado_max'     => 1.0,
                'condicoes_mare' => 'favoravel',
                'recomendada'    => false,
                'rota_direta'    => true,
                'warnings'       => [],
            ],
            [
                'routinav_id'    => 684,
                'nome'           => 'Bico → Boco',
                'via'            => 'por S. Jacinto',
                'distancia_nm'   => 14.03,
                'gpx_file'       => null,
                'cais_partida'   => $this->dock('Bico'),
                'cais_chegada'   => $this->dock('Boco'),
                'calado_max'     => 0.3,
                'condicoes_mare' => 'estofo',
                'recomendada'    => true,
                'rota_direta'    => true,
                'descricao'      => 'Rota TOP para barcos de calado <0,3m. Partir antes da PM para chegar ao Boco em estofo.',
                'warnings'       => [],
            ],
            [
                'routinav_id'    => 732,
                'nome'           => 'Bico → Boco',
                'via'            => 'pela Testada',
                'distancia_nm'   => 12.09,
                'gpx_file'       => null,
                'cais_partida'   => $this->dock('Bico'),
                'cais_chegada'   => $this->dock('Boco'),
                'calado_max'     => 0.3,
                'condicoes_mare' => 'estofo',
                'recomendada'    => true,
                'rota_direta'    => false,
                'descricao'      => 'Rota TOP para barcos de calado <0,3m. Partir antes da PM para chegar ao Boco em estofo.',
                'warnings'       => [],
            ],
            [
                'routinav_id'    => 225,
                'nome'           => 'Bico → Carregal',
                'via'            => null,
                'distancia_nm'   => 9.48,
                'gpx_file'       => null,
                'cais_partida'   => $this->dock('Bico'),
                'cais_chegada'   => $this->dock('Carregal (destino)'),
                'calado_max'     => 1.0,
                'condicoes_mare' => 'favoravel',
                'recomendada'    => false,
                'rota_direta'    => true,
                'warnings'       => ['À chegada ao Carregal há pontos muito baixos mesmo em BM — considerar rota alternativa'],
            ],
            [
                'routinav_id'    => 249,
                'nome'           => 'Bico → Costa Nova',
                'via'            => 'pela Testada',
                'distancia_nm'   => 8.91,
                'gpx_file'       => '106_BL3_CaisBico__CM3_CostaNova.gpx',
                'cais_partida'   => $this->dock('Bico'),
                'cais_chegada'   => $this->dock('Costa Nova'),
                'calado_max'     => 1.0,
                'condicoes_mare' => 'favoravel',
                'recomendada'    => false,
                'rota_direta'    => false,
                'warnings'       => ['Zona à volta do Forte da Barra com sonda de 15m adquirida — a corrigir'],
            ],
            [
                'routinav_id'    => 945,
                'nome'           => 'Bico → Ponte da Barra',
                'via'            => 'pela Testada',
                'distancia_nm'   => 8.19,
                'gpx_file'       => null,
                'cais_partida'   => $this->dock('Bico'),
                'cais_chegada'   => $this->dock('Ponte da Barra'),
                'calado_max'     => 1.0,
                'condicoes_mare' => 'favoravel',
                'recomendada'    => false,
                'rota_direta'    => true,
                'descricao'      => 'Rota de muito fácil execução.',
                'warnings'       => [],
            ],
            [
                'routinav_id'    => 402,
                'nome'           => 'Bico → Ribeira de Pardelhas',
                'via'            => null,
                'distancia_nm'   => 1.27,
                'gpx_file'       => null,
                'cais_partida'   => $this->dock('Bico'),
                'cais_chegada'   => $this->dock('Ribeira de Pardelhas'),
                'calado_max'     => 0.5,
                'condicoes_mare' => 'favoravel',
                'recomendada'    => false,
                'rota_direta'    => true,
                'descricao'      => 'Para barcos de calado <0,5m.',
                'warnings'       => [],
            ],
            [
                'routinav_id'    => 375,
                'nome'           => 'Bico → S. Jacinto',
                'via'            => 'pela Testada',
                'distancia_nm'   => 8.19,
                'gpx_file'       => null,
                'cais_partida'   => $this->dock('Bico'),
                'cais_chegada'   => $this->dock('S. Jacinto'),
                'calado_max'     => 1.0,
                'condicoes_mare' => 'favoravel',
                'recomendada'    => false,
                'rota_direta'    => true,
                'descricao'      => 'Rota de muito fácil execução.',
                'warnings'       => [],
            ],
            [
                'routinav_id'    => 237,
                'nome'           => 'Bico → Torreira',
                'via'            => 'pela margem Nascente',
                'distancia_nm'   => 3.33,
                'gpx_file'       => null,
                'cais_partida'   => $this->dock('Bico'),
                'cais_chegada'   => $this->dock('Torreira'),
                'calado_max'     => 1.0,
                'condicoes_mare' => 'qualquer',
                'recomendada'    => false,
                'rota_direta'    => true,
                'descricao'      => 'Rota de fácil execução pela margem Nascente.',
                'warnings'       => [],
            ],
            [
                'routinav_id'    => 300,
                'nome'           => 'Bico → Torreira',
                'via'            => 'pela margem Poente',
                'distancia_nm'   => 4.49,
                'gpx_file'       => null,
                'cais_partida'   => $this->dock('Bico'),
                'cais_chegada'   => $this->dock('Torreira'),
                'calado_max'     => 1.0,
                'condicoes_mare' => 'qualquer',
                'recomendada'    => false,
                'rota_direta'    => true,
                'descricao'      => 'Rota de fácil execução pela margem Poente.',
                'warnings'       => [],
            ],
            [
                'routinav_id'    => 150,
                'nome'           => 'Bico → Vagueira',
                'via'            => null,
                'distancia_nm'   => 12.15,
                'gpx_file'       => null,
                'cais_partida'   => $this->dock('Bico'),
                'cais_chegada'   => $this->dock('Vagueira'),
                'calado_max'     => 1.0,
                'condicoes_mare' => 'favoravel',
                'recomendada'    => false,
                'rota_direta'    => true,
                'warnings'       => ['Do Forte da Barra até à Ponte da Barra há segmentos adquiridos por cima de sequeiros — a corrigir'],
            ],
            [
                'routinav_id'    => 234,
                'nome'           => 'Bico → Varela',
                'via'            => null,
                'distancia_nm'   => 5.23,
                'gpx_file'       => null,
                'cais_partida'   => $this->dock('Bico'),
                'cais_chegada'   => $this->dock('Varela'),
                'calado_max'     => 1.0,
                'condicoes_mare' => 'favoravel',
                'recomendada'    => false,
                'rota_direta'    => true,
                'warnings'       => ['Rota não estava a aparecer — verificar importação'],
            ],

            // ============================================================
            // CAIS DE PARTIDA: SALREU
            // ============================================================

            [
                'routinav_id'    => 93,
                'nome'           => 'Salreu → APARA',
                'via'            => 'pela Testada (invertida)',
                'distancia_nm'   => 10.69,
                'gpx_file'       => null,
                'cais_partida'   => $this->dock('Salreu'),
                'cais_chegada'   => $this->dock('APARA'),
                'calado_max'     => 1.0,
                'condicoes_mare' => 'favoravel',
                'recomendada'    => false,
                'rota_direta'    => false,
                'warnings'       => ['Outlier após Salreu a corrigir'],
            ],
            [
                'routinav_id'    => 95,
                'nome'           => 'Salreu → APARA',
                'via'            => 'por S. Jacinto',
                'distancia_nm'   => 10.40,
                'gpx_file'       => null,
                'cais_partida'   => $this->dock('Salreu'),
                'cais_chegada'   => $this->dock('APARA'),
                'calado_max'     => 1.0,
                'condicoes_mare' => 'favoravel',
                'recomendada'    => false,
                'rota_direta'    => true,
                'warnings'       => ['Outlier após Salreu a corrigir'],
            ],
            [
                'routinav_id'    => 975,
                'nome'           => 'Salreu → Bico',
                'via'            => null,
                'distancia_nm'   => 3.69,
                'gpx_file'       => null,
                'cais_partida'   => $this->dock('Salreu'),
                'cais_chegada'   => $this->dock('Bico'),
                'calado_max'     => 1.0,
                'condicoes_mare' => 'favoravel',
                'recomendada'    => false,
                'rota_direta'    => true,
                'warnings'       => ['Parte inicial com valores 99999 — cortar até posição 52'],
            ],
            [
                'routinav_id'    => 381,
                'nome'           => 'Salreu → Lota',
                'via'            => null,
                'distancia_nm'   => 10.82,
                'gpx_file'       => null,
                'cais_partida'   => $this->dock('Salreu'),
                'cais_chegada'   => $this->dock('Lota'),
                'calado_max'     => 1.0,
                'condicoes_mare' => 'favoravel',
                'recomendada'    => false,
                'rota_direta'    => true,
                'warnings'       => ['Outlier após Salreu a corrigir'],
            ],
            [
                'routinav_id'    => 71,
                'nome'           => 'Salreu → Torreira',
                'via'            => 'por cima do sequeiro',
                'distancia_nm'   => 7.72,
                'gpx_file'       => null,
                'cais_partida'   => $this->dock('Salreu'),
                'cais_chegada'   => $this->dock('Torreira'),
                'calado_max'     => 0.3,
                'condicoes_mare' => 'estofo',
                'recomendada'    => false,
                'rota_direta'    => true,
                'warnings'       => ['Passa por cima de sequeiro — usar apenas em estofo e baixo calado; outlier após Salreu a corrigir'],
            ],
            [
                'routinav_id'    => 387,
                'nome'           => 'Salreu → Torreira',
                'via'            => 'fora do sequeiro',
                'distancia_nm'   => 7.78,
                'gpx_file'       => null,
                'cais_partida'   => $this->dock('Salreu'),
                'cais_chegada'   => $this->dock('Torreira'),
                'calado_max'     => 1.0,
                'condicoes_mare' => 'favoravel',
                'recomendada'    => false,
                'rota_direta'    => true,
                'warnings'       => ['Outlier após Salreu a corrigir'],
            ],

            // ============================================================
            // CAIS DE PARTIDA: MORANZEL
            // ============================================================

            [
                'routinav_id'    => 786,
                'nome'           => 'Moranzel → Boco',
                'via'            => 'por S. Jacinto',
                'distancia_nm'   => 11.77,
                'gpx_file'       => null,
                'cais_partida'   => $this->dock('Moranzel'),
                'cais_chegada'   => $this->dock('Boco'),
                'calado_max'     => 0.3,
                'condicoes_mare' => 'estofo',
                'recomendada'    => false,
                'rota_direta'    => true,
                'descricao'      => 'Para barcos de calado <0,3m.',
                'warnings'       => [],
            ],
            [
                'routinav_id'    => 789,
                'nome'           => 'Moranzel → Boco',
                'via'            => 'pela Testada',
                'distancia_nm'   => 15.10,
                'gpx_file'       => null,
                'cais_partida'   => $this->dock('Moranzel'),
                'cais_chegada'   => $this->dock('Boco'),
                'calado_max'     => 0.3,
                'condicoes_mare' => 'estofo',
                'recomendada'    => false,
                'rota_direta'    => false,
                'descricao'      => 'Para barcos de calado <0,3m.',
                'warnings'       => [],
            ],
            [
                'routinav_id'    => 201,
                'nome'           => 'Moranzel → Carregal',
                'via'            => null,
                'distancia_nm'   => 8.51,
                'gpx_file'       => null,
                'cais_partida'   => $this->dock('Moranzel'),
                'cais_chegada'   => $this->dock('Carregal (destino)'),
                'calado_max'     => 1.0,
                'condicoes_mare' => 'favoravel',
                'recomendada'    => false,
                'rota_direta'    => true,
                'warnings'       => [],
            ],
            [
                'routinav_id'    => 498,
                'nome'           => 'Moranzel → Costa Nova',
                'via'            => 'à vela',
                'distancia_nm'   => 7.33,
                'gpx_file'       => null,
                'cais_partida'   => $this->dock('Moranzel'),
                'cais_chegada'   => $this->dock('Costa Nova'),
                'calado_max'     => 1.0,
                'condicoes_mare' => 'favoravel',
                'recomendada'    => false,
                'rota_direta'    => true,
                'warnings'       => ['No mobile a rota desaparecia antes de simular — verificar após importação GPX'],
            ],
            [
                'routinav_id'    => 612,
                'nome'           => 'Moranzel → Gafanha Aquém',
                'via'            => 'por S. Jacinto',
                'distancia_nm'   => 6.90,
                'gpx_file'       => null,
                'cais_partida'   => $this->dock('Moranzel'),
                'cais_chegada'   => $this->dock('Gafanha Aquém'),
                'calado_max'     => 1.0,
                'condicoes_mare' => 'favoravel',
                'recomendada'    => false,
                'rota_direta'    => true,
                'warnings'       => [],
            ],
            [
                'routinav_id'    => 909,
                'nome'           => 'Moranzel → Lota',
                'via'            => 'por S. Jacinto',
                'distancia_nm'   => 9.93,
                'gpx_file'       => null,
                'cais_partida'   => $this->dock('Moranzel'),
                'cais_chegada'   => $this->dock('Lota'),
                'calado_max'     => 1.0,
                'condicoes_mare' => 'favoravel',
                'recomendada'    => false,
                'rota_direta'    => true,
                'warnings'       => ['Em parte da rota não há informação de maré (cor roxa)'],
            ],
            [
                'routinav_id'    => 204,
                'nome'           => 'Moranzel → Ribeira das Teixugueiras',
                'via'            => null,
                'distancia_nm'   => 5.7,
                'gpx_file'       => null,
                'cais_partida'   => $this->dock('Moranzel'),
                'cais_chegada'   => $this->dock('Ribeira das Teixugueiras'),
                'calado_max'     => 1.0,
                'condicoes_mare' => 'qualquer',
                'recomendada'    => false,
                'rota_direta'    => true,
                'descricao'      => 'Rota OK e realizável com várias condições de maré.',
                'warnings'       => [],
            ],
            [
                'routinav_id'    => 834,
                'nome'           => 'Moranzel → S. Jacinto',
                'via'            => null,
                'distancia_nm'   => 4.91,
                'gpx_file'       => null,
                'cais_partida'   => $this->dock('Moranzel'),
                'cais_chegada'   => $this->dock('S. Jacinto'),
                'calado_max'     => 1.0,
                'condicoes_mare' => 'favoravel',
                'recomendada'    => false,
                'rota_direta'    => true,
                'warnings'       => ['Cortar início (começar mais a Sul); eliminar outliers em frente à entrada para a Cale do Ouro'],
            ],
            [
                'routinav_id'    => 207,
                'nome'           => 'Moranzel → Torreira',
                'via'            => null,
                'distancia_nm'   => 2.21,
                'gpx_file'       => null,
                'cais_partida'   => $this->dock('Moranzel'),
                'cais_chegada'   => $this->dock('Torreira'),
                'calado_max'     => 99.0, // qualquer maré
                'condicoes_mare' => 'qualquer',
                'recomendada'    => false,
                'rota_direta'    => true,
                'descricao'      => 'Esta rota pode-se fazer com qualquer altura de maré.',
                'warnings'       => [],
            ],
            [
                'routinav_id'    => 510,
                'nome'           => 'Moranzel → Torreira',
                'via'            => 'à vela',
                'distancia_nm'   => 3.57,
                'gpx_file'       => null,
                'cais_partida'   => $this->dock('Moranzel'),
                'cais_chegada'   => $this->dock('Torreira'),
                'calado_max'     => 1.0,
                'condicoes_mare' => 'favoravel',
                'recomendada'    => false,
                'rota_direta'    => true,
                'descricao'      => 'Rota interessante, feita à bolina de Sul para Norte.',
                'warnings'       => ['Duas zonas de outliers a corrigir'],
            ],
            [
                'routinav_id'    => 984,
                'nome'           => 'Moranzel → Vagueira',
                'via'            => null,
                'distancia_nm'   => 10.52,
                'gpx_file'       => null,
                'cais_partida'   => $this->dock('Moranzel'),
                'cais_chegada'   => $this->dock('Vagueira'),
                'calado_max'     => 1.0,
                'condicoes_mare' => 'favoravel',
                'recomendada'    => false,
                'rota_direta'    => true,
                'warnings'       => [
                    'Outliers no canal do Forte da Barra e depois da Ponte da Barra a corrigir',
                    'Outliers partilhados com rota 834 a corrigir',
                ],
            ],

            // ============================================================
            // CAIS DE PARTIDA: ARIEIROS (Veia da Testada)
            // ============================================================

            [
                'routinav_id'    => 438,
                'nome'           => 'Arieiros → Ilha dos Ovos',
                'via'            => null,
                'distancia_nm'   => 3.4,
                'gpx_file'       => null,
                'cais_partida'   => $this->dock('Arieiros'),
                'cais_chegada'   => $this->dock('Ilha dos Ovos'),
                'calado_max'     => 0.5,
                'condicoes_mare' => 'mares_vivas',
                'recomendada'    => false,
                'rota_direta'    => true,
                'descricao'      => 'Rota interessante que sai do lado Nascente da Testada, passa pela Veia da Testada, atravessa a Cale do Parrachil e entra pela Cale do Amoroso adentro (numa zona muito afunilada e baixa), até à Ilha dos Ovos.',
                'warnings'       => ['Parte inicial com poucos pontos GPS; segmento final junto à Ilha dos Ovos a cortar (passa por terra)'],
            ],

            // ============================================================
            // CAIS DE PARTIDA: MOACHA NORTE
            // ============================================================

            [
                'routinav_id'    => 414,
                'nome'           => 'Moacha Norte → Baía dos Lavacos',
                'via'            => 'por S. Jacinto',
                'distancia_nm'   => 2.50,
                'gpx_file'       => null,
                'cais_partida'   => $this->dock('Moacha Norte'),
                'cais_chegada'   => $this->dock('Baía dos Lavacos'),
                'calado_max'     => 1.0,
                'condicoes_mare' => 'favoravel',
                'recomendada'    => false,
                'rota_direta'    => true,
                'warnings'       => ['Parte inicial com poucos pontos GPS'],
            ],

            // ============================================================
            // CAIS DE PARTIDA: ILHA DOS OVOS / AMOROSO
            // ============================================================

            [
                'routinav_id'    => 432,
                'nome'           => 'Ilha dos Ovos → Arieiros',
                'via'            => 'pela Veia da Testada',
                'distancia_nm'   => 3.40,
                'gpx_file'       => null,
                'cais_partida'   => $this->dock('Ilha dos Ovos'),
                'cais_chegada'   => $this->dock('Arieiros'),
                'calado_max'     => 0.5,
                'condicoes_mare' => 'mares_vivas',
                'recomendada'    => false,
                'rota_direta'    => false,
                'descricao'      => 'Realizar em marés vivas ou com barcos de calado <0,5m.',
                'warnings'       => [],
            ],
            [
                'routinav_id'    => 435,
                'nome'           => 'Ilha dos Ovos → Bico',
                'via'            => 'pela Veia da Testada',
                'distancia_nm'   => 5.12,
                'gpx_file'       => null,
                'cais_partida'   => $this->dock('Ilha dos Ovos'),
                'cais_chegada'   => $this->dock('Bico'),
                'calado_max'     => 0.5,
                'condicoes_mare' => 'mares_vivas',
                'recomendada'    => false,
                'rota_direta'    => false,
                'descricao'      => 'Realizar em marés vivas ou com barcos de calado <0,5m.',
                'warnings'       => [],
            ],
            [
                'routinav_id'    => 444,
                'nome'           => 'Ilha dos Ovos → Carregal',
                'via'            => 'pela Marinha do Sal',
                'distancia_nm'   => 14.55,
                'gpx_file'       => null,
                'cais_partida'   => $this->dock('Ilha dos Ovos'),
                'cais_chegada'   => $this->dock('Carregal (destino)'),
                'calado_max'     => 0.3,
                'condicoes_mare' => 'estofo',
                'recomendada'    => true,
                'rota_direta'    => false,
                'descricao'      => 'Rota muito interessante e, simultaneamente, muito técnica, pois só poderá ser realizada em condições de estofo da maré e com barcos de baixo calado. Partindo-se da Ilha dos Ovos, começa-se por navegar pela Cale do Amoroso, para logo se alcançar a Cale do Parrachil através de um estreito canalete. Daí em diante, segue-se, de Sul para Norte, pela sinuosa Veia da Testada, ficando do lado Nascente a Ilha da Pedra e do lado Poente a Ilha da Testada, passando-se mais acima pelos Arieiros e indo-se desembocar na Boca do Rio Velho (antiga Foz do Rio Vouga – antes da construção do Rio Novo do Príncipe). A partir daqui passa-se a navegar para Poente, passando-se pelo Bico da Murtosa e pela entrada da Ribeira de Pardelhas. Fica-se, então, com a possibilidade de navegar numa diagonal em direção à Torreira, para depois se atingir a Ponte da Varela. Navega-se, a seguir, para dentro da Marinha do Sal para se atingir o Canal de Ovar já mais a Norte, passando-se pelo Torrão do Lameiro, Areinho e, finalmente, chegando-se ao Carregal.',
                'warnings'       => ['Vários outliers perto do Torrão do Lameiro corrigidos'],
            ],
            [
                'routinav_id'    => 429,
                'nome'           => 'Ilha dos Ovos → Salreu',
                'via'            => 'pela Testada',
                'distancia_nm'   => 7.97,
                'gpx_file'       => null,
                'cais_partida'   => $this->dock('Ilha dos Ovos'),
                'cais_chegada'   => $this->dock('Salreu'),
                'calado_max'     => 0.5,
                'condicoes_mare' => 'mares_vivas',
                'recomendada'    => false,
                'rota_direta'    => false,
                'descricao'      => 'Realizar em marés vivas ou com barcos de calado <0,5m.',
                'warnings'       => ['Verificar desfasamento UTC nas horas de PM/BM apresentadas'],
            ],

            // ============================================================
            // CAIS DE PARTIDA: RIO NOVO DO PRÍNCIPE
            // ============================================================

            [
                'routinav_id'    => 969,
                'nome'           => 'Rio Novo do Príncipe → ANGE',
                'via'            => 'por S. Jacinto',
                'distancia_nm'   => 13.81,
                'gpx_file'       => null,
                'cais_partida'   => $this->dock('Rio Novo do Príncipe'),
                'cais_chegada'   => $this->dock('ANGE'),
                'calado_max'     => 1.0,
                'condicoes_mare' => 'favoravel',
                'recomendada'    => true,
                'rota_direta'    => true,
                'descricao'      => 'Rota muito interessante que sai do Rio Novo do Príncipe numa zona perfeitamente navegável até ao dique de madeira (em Vilarinho). Partindo-se do Rio Novo do Príncipe, começa-se por navegar em direção à Ilha do Parrachil, que será contornada pela sua margem Oeste quando se começar a navegar para Norte em direção à Ilha de Matadouce. Na transição entre estas duas ilhas encontra-se a entrada da sinuosa Veia da Testada, ficando do lado Nascente a Ilha da Pedra e do lado Poente a Ilha da Testada, passando-se mais acima pelos Arieiros e indo-se desembocar na Boca do Rio Velho. A partir daqui passa-se a navegar para Poente, passando-se pelo Bico da Murtosa e pela entrada da Ribeira de Pardelhas. Fica-se, então, com a possibilidade de navegar numa diagonal em direção ao Bico do Moranzel e, daí, sempre para Sul em direção a São Jacinto. Já depois de São Jacinto, entra-se para o canalete do Forte da Barra para alcançar o Canal de Ílhavo, passando-se pela APARA e, logo a seguir, por debaixo da Ponte da Barra, deixando-se para Poente a Costa Nova e para Nascente a Gafanha da Embarcação, entrando-se, finalmente, no canal de acesso à Marina da ANGE.',
                'warnings'       => [],
            ],
            [
                'routinav_id'    => 474,
                'nome'           => 'Rio Novo do Príncipe → APARA',
                'via'            => 'pelo Canal do Espinheiro',
                'distancia_nm'   => 5.76,
                'gpx_file'       => null,
                'cais_partida'   => $this->dock('Rio Novo do Príncipe'),
                'cais_chegada'   => $this->dock('APARA'),
                'calado_max'     => 1.0,
                'condicoes_mare' => 'favoravel',
                'recomendada'    => false,
                'rota_direta'    => true,
                'warnings'       => [],
            ],
            [
                'routinav_id'    => 540,
                'nome'           => 'Rio Novo do Príncipe → Lota',
                'via'            => 'pelo Canal do Espinheiro',
                'distancia_nm'   => 7.12,
                'gpx_file'       => null,
                'cais_partida'   => $this->dock('Rio Novo do Príncipe'),
                'cais_chegada'   => $this->dock('Lota'),
                'calado_max'     => 1.0,
                'condicoes_mare' => 'qualquer',
                'recomendada'    => false,
                'rota_direta'    => true,
                'warnings'       => [],
            ],
            [
                'routinav_id'    => 876,
                'nome'           => 'Rio Novo do Príncipe → Lota',
                'via'            => 'pela Cale de Bolhões',
                'distancia_nm'   => 3.01,
                'gpx_file'       => null,
                'cais_partida'   => $this->dock('Rio Novo do Príncipe'),
                'cais_chegada'   => $this->dock('Lota'),
                'calado_max'     => 0.5,
                'condicoes_mare' => 'mares_vivas',
                'recomendada'    => false,
                'rota_direta'    => true,
                'descricao'      => 'Realizar em marés vivas ou com barcos de calado <0,5m.',
                'warnings'       => [],
            ],
            [
                'routinav_id'    => 939,
                'nome'           => 'Rio Novo do Príncipe → S. Jacinto',
                'via'            => 'pelo Canal do Espinheiro',
                'distancia_nm'   => 4.02,
                'gpx_file'       => null,
                'cais_partida'   => $this->dock('Rio Novo do Príncipe'),
                'cais_chegada'   => $this->dock('S. Jacinto'),
                'calado_max'     => 1.0,
                'condicoes_mare' => 'favoravel',
                'recomendada'    => false,
                'rota_direta'    => true,
                'warnings'       => [],
            ],

            // ============================================================
            // CAIS DE PARTIDA: PARRACHIL
            // ============================================================

            [
                'routinav_id'    => 525,
                'nome'           => 'Parrachil → APARA',
                'via'            => null,
                'distancia_nm'   => 4.22,
                'gpx_file'       => null,
                'cais_partida'   => $this->dock('Parrachil'),
                'cais_chegada'   => $this->dock('APARA'),
                'calado_max'     => 99.0,
                'condicoes_mare' => 'qualquer',
                'recomendada'    => false,
                'rota_direta'    => true,
                'descricao'      => 'Potencialmente realizável com qualquer condição de maré.',
                'warnings'       => [],
            ],
            [
                'routinav_id'    => 819,
                'nome'           => 'Parrachil → APARA',
                'via'            => null,
                'distancia_nm'   => 4.13,
                'gpx_file'       => null,
                'cais_partida'   => $this->dock('Parrachil'),
                'cais_chegada'   => $this->dock('APARA'),
                'calado_max'     => 99.0,
                'condicoes_mare' => 'qualquer',
                'recomendada'    => false,
                'rota_direta'    => true,
                'descricao'      => 'Potencialmente realizável com qualquer condição de maré.',
                'warnings'       => [],
            ],
            [
                'routinav_id'    => 1020,
                'nome'           => 'Parrachil → Marégrafo da Barra',
                'via'            => null,
                'distancia_nm'   => 6.93,
                'gpx_file'       => null,
                'cais_partida'   => $this->dock('Parrachil'),
                'cais_chegada'   => $this->dock('Marégrafo da Barra'),
                'calado_max'     => 1.0,
                'condicoes_mare' => 'favoravel',
                'recomendada'    => false,
                'rota_direta'    => true,
                'warnings'       => ['Cortar início e fim para coincidir com os markers'],
            ],

            // ============================================================
            // CAIS DE PARTIDA: LAVACOS
            // ============================================================

            [
                'routinav_id'    => 939, // nota: mesmo routinav_id que Rio Novo → S. Jacinto — possível erro no PDF
                'nome'           => 'Lavacos → Lota',
                'via'            => null,
                'distancia_nm'   => 7.73,
                'gpx_file'       => null,
                'cais_partida'   => $this->dock('Lavacos'),
                'cais_chegada'   => $this->dock('Lota'),
                'calado_max'     => 99.0,
                'condicoes_mare' => 'qualquer',
                'recomendada'    => false,
                'rota_direta'    => true,
                'descricao'      => 'Rota OK e, aparentemente, de realização com qualquer condição de maré até à cale dos Bolhões.',
                'warnings'       => [],
            ],
            [
                'routinav_id'    => 363,
                'nome'           => 'Lavacos → Moranzel',
                'via'            => 'à vela',
                'distancia_nm'   => 3.59,
                'gpx_file'       => null,
                'cais_partida'   => $this->dock('Lavacos'),
                'cais_chegada'   => $this->dock('Moranzel (destino)'),
                'calado_max'     => 1.0,
                'condicoes_mare' => 'qualquer',
                'recomendada'    => true,
                'rota_direta'    => true,
                'descricao'      => 'Rota interessante na perspetiva que foi realizada por um dos participantes do SisMAR enquanto este navegava à bolina Ria acima. A rota permite evidenciar os limites de navegabilidade limitados a nascente pelos sequeiros que afloram na zona da Berbigoeira, no Pragal (mesmo à entrada da famosa cale do Ouro) e nas ilhas da Gaivota e dos Ovos.',
                'warnings'       => [],
            ],
            [
                'routinav_id'    => 330,
                'nome'           => 'Lavacos → Torreira',
                'via'            => 'à vela',
                'distancia_nm'   => 7.33,
                'gpx_file'       => null,
                'cais_partida'   => $this->dock('Lavacos'),
                'cais_chegada'   => $this->dock('Torreira'),
                'calado_max'     => 1.0,
                'condicoes_mare' => 'favoravel',
                'recomendada'    => true,
                'rota_direta'    => true,
                'descricao'      => 'Rota interessante na perspetiva que foi realizada por um dos participantes do SisMAR enquanto este navegava à bolina Ria acima. A rota permite evidenciar os limites de navegabilidade limitados a nascente pelos sequeiros que afloram na zona da Berbigoeira, no Pragal e nas ilhas da Gaivota e dos Ovos. O percurso continua à bolina, após o Moranzel, mas é feito maioritariamente por cima de diversos sequeiros. Contudo, desde que em condições de altura de maré favoráveis e mesmo com barcos de calado de 1 metro, todo o percurso é navegável.',
                'warnings'       => ['Cortar voltinhas iniciais'],
            ],
            [
                'routinav_id'    => 1149,
                'nome'           => 'Lavacos → Torreira',
                'via'            => 'por dentro do molhe',
                'distancia_nm'   => 6.68,
                'gpx_file'       => null,
                'cais_partida'   => $this->dock('Lavacos'),
                'cais_chegada'   => $this->dock('Torreira'),
                'calado_max'     => 1.0,
                'condicoes_mare' => 'favoravel',
                'recomendada'    => true,
                'rota_direta'    => true,
                'descricao'      => 'Rota interessante em que a maior particularidade se situa no seu início. Esta começa na praia de Lavacos situada por dentro do molhe separador do Canal de São Jacinto e do Canal da Vila. A parte inicial, até à Baía de Lavacos, é toda realizada por dentro deste molhe de onde se avista todo o areal de Lavacos e respetivas praias. À saída do molhe, a rota segue para a margem poente do Canal de São Jacinto, passando junto à zona da antiga balança, Parque de Campismo de São Jacinto, Pragal, Ilhas da Gaivota e dos Ovos e Cabeços do Cão e do Travessadouro, atingindo-se, depois, o Moranzel e a Pousada da Ria. Com início na Praia de Lavacos por dentro do molhe do separador do Canal de São Jacinto e do Canal da Vila.',
                'warnings'       => [],
            ],

        ];
    }
}
